---
name: Run tests and package firmware
on:
  workflow_dispatch: 
  push:
    branches:
      - 'main'
      - '[0-9]+.[0-9]+'
    tags:
      - v*
    paths: &trigger-paths
      - '.github/workflows/build_fw.yml'
      - 'cmake/**'
      - 'radio/**'
      - 'tools/build-gh.sh'
      - '.gitmodules'
      - 'CMakeLists.txt'
  pull_request:
    paths: *trigger-paths

jobs:
  build:
    name: Build Horus X12S Firmware
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x12s]
    container:
      image: ghcr.io/edgetx/edgetx-dev:latest
      volumes:
        - ${{ github.workspace }}:/src
    steps:
      - name: Check out the repo
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Compile Custom Firmware
        run: |
          cmake -B build -DPCB=X12S -DGIMBAL=FLY_SKY -DPCBS_TO_BUILD=X12S
          cmake --build build -j4 --target firmware
          find build -name "*.bin" -exec cp {} . \;

      - name: Upload Firmware Binary
        uses: actions/upload-artifact@v7
        with:
          name: edgetx-x12s-flysky-gimbals
          path: "*.bin"
          retention-days: 7
          if-no-files-found: error
